a = input("Input First Number: ")
b = input("Input Second Number: ")

print(f"Addition: {a} + {b} = {a+b}")
print(f"Subtraction: {a} - {b} = {a-b}")
print(f"Multiplication: {a} * {b} = {a*b}")
print(f"Division: {a} / {b} = {a/b}")
print(f"Floor Division: {a} // {b}) = {a//b}")
print(f"Modulus: {a} % {b} = {a%b}")
print(f"Exponent: {a} ** {b} = {a**b}")
